name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Add requirements for tests
        shell: bash
        run: |
          cd tests
          npx tailwind init --ts
          sed -i 's/from "tailwindcss";/from "npm:tailwindcss";' tailwind.config.ts
          rm tailwind.config.ts
          echo '.roboto { font-family: Roboto, sans-serif; }' > test.css
          cd ..

      - name: Run tests
        run: deno test -A
