name: Test

on:
  push:
    branches: ["main", "next"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Add requirements for tests
        run: |
          npm install tailwindcss --save-dev
          npm ci
          npx tailwindcss init --ts
      - name: Add test CSS
        shell: bash
        run: |
          echo '.roboto { font-family: Roboto, sans-serif; }' > test.css
      - name: Upload test directory
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: |
            tailwind.config.ts
            test.css
          retention-days: 1
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
      - name: Download test directory
        uses: actions/download-artifact@v2
        with:
          name: tests
          path: test
      - name: Add npm specifier
        run: |
          sed 's/tailwindcss/npm:tailwindcss/g' test/tailwind.config.ts > test/_tailwind.config.ts
          echo '{"imports": {"tailwindcss": "npm:tailwindcss@3.3.5"}}' > import_map.json
          rm test/tailwind.config.ts
      - name: Format for Deno
        run: |
          deno fmt test/_tailwind.config.ts
          deno fmt import_map.json
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
